pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/shahraza0098/wipro-assignment.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('milestone_four') {
                    bat 'docker build -t milestone-four .'
                }
            }
        }

        stage('Run Tests In Docker') {
            steps {
                bat 'docker run --rm milestone-four'
            }
        }
    }

    post {
        success {
            echo 'Docker Build Successful'
        }

        failure {
            echo 'Docker Build Failed'
        }
    }
}